#pragma once


/* image size definition */
#define IMG_SIZE_LOGO0              20008			    /* 200*50 logo alfawise     */
#define IMG_SIZE_LOGO1              48008				/* 200*120 logo iformer     */
#define IMG_SIZE_LOGO2              18408				/* 230*40 logo longer       */

#define IMG_SIZE_CAPTION            2888				/* 90*16 caption            */
//#define pic_size_button_home 11208			        /* 70*80 home button        */
#define IMG_SIZE_WARNING_TEMP       2922		        /* 31*47 temper warning     */
#define IMG_SIZE_BUTTON_NORMAL      6058			    /* 55*55 normal button      */
#define IMG_SIZE_BUTTON_ARROW       7158			    /* 65*55 arrow button       */
#define IMG_SIZE_BUTTON_DISTANCE    4408 		        /* 55*40 distance button    */
#define IMG_SIZE_ICON_MINI          1808				/* 30*30 mini icon          */
//#define pic_size_button_leveling 13608		        /* 85*80 leveling button    */
#define IMG_SIZE_BUTTON_FEED        7378			    /* 67*55 feed button        */
#define IMG_SIZE_DIALOG_BODY        60008			    /* 200*150 dialog body      */
#define IMG_SIZE_BUTTON_BED         4108			    /* 50*41 bed_on/off button  */

/* image address definition */

/* launch logo */
#define  IMG_ADDR_STARTUP_LOGO_0 (0u)

/* menu home */
#define  IMG_ADDR_CAPTION_HOME                  (IMG_ADDR_STARTUP_LOGO_0 + IMG_SIZE_LOGO0)
#define  IMG_ADDR_BUTTON_MOVE                   (IMG_ADDR_CAPTION_HOME + IMG_SIZE_CAPTION)
#define  IMG_ADDR_BUTTON_MOVE_PRESSED           (IMG_ADDR_BUTTON_MOVE + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_FILE                   (IMG_ADDR_BUTTON_MOVE_PRESSED + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_FILE_PRESSED           (IMG_ADDR_BUTTON_FILE + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_EXTRUDE                (IMG_ADDR_BUTTON_FILE_PRESSED + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_EXTRUDE_PRESSED        (IMG_ADDR_BUTTON_EXTRUDE + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_PREHEAT                (IMG_ADDR_BUTTON_EXTRUDE_PRESSED + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_PREHEAT_PRESSED        (IMG_ADDR_BUTTON_PREHEAT + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_LEVELING               (IMG_ADDR_BUTTON_PREHEAT_PRESSED + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_LEVELING_PRESSED       (IMG_ADDR_BUTTON_LEVELING + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_RECOVERY               (IMG_ADDR_BUTTON_LEVELING_PRESSED + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_RECOVERY_PRESSED       (IMG_ADDR_BUTTON_RECOVERY + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_RECOVERY_DISABLE       (IMG_ADDR_BUTTON_RECOVERY_PRESSED + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_MORE                   (IMG_ADDR_BUTTON_RECOVERY_DISABLE + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_MORE_PRESSED           (IMG_ADDR_BUTTON_MORE + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_SETTINGS               (IMG_ADDR_BUTTON_MORE_PRESSED + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_SETTINGS_PRESSED       (IMG_ADDR_BUTTON_SETTINGS + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_ABOUT                  (IMG_ADDR_BUTTON_SETTINGS_PRESSED + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_ABOUT_PRESSED          (IMG_ADDR_BUTTON_ABOUT + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_LANGUAGE               (IMG_ADDR_BUTTON_ABOUT_PRESSED + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_LANGUAGE_PRESSED       (IMG_ADDR_BUTTON_LANGUAGE + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_RETURN                 (IMG_ADDR_BUTTON_LANGUAGE_PRESSED + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_RETURN_PRESSED         (IMG_ADDR_BUTTON_RETURN + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_WARNING_COLD_BED              (IMG_ADDR_BUTTON_RETURN_PRESSED + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_WARNING_COLD_HEAD             (IMG_ADDR_WARNING_COLD_BED + IMG_SIZE_WARNING_TEMP)
#define  IMG_ADDR_WARNING_HOT_BED               (IMG_ADDR_WARNING_COLD_HEAD + IMG_SIZE_WARNING_TEMP)
#define  IMG_ADDR_WARNING_HOT_HEAD              (IMG_ADDR_WARNING_HOT_BED + IMG_SIZE_WARNING_TEMP)

/* menu move */
#define  IMG_ADDR_CAPTION_MOVE                  (IMG_ADDR_WARNING_HOT_HEAD + IMG_SIZE_WARNING_TEMP)
#define  IMG_ADDR_BUTTON_HOME_ALL               (IMG_ADDR_CAPTION_MOVE + IMG_SIZE_CAPTION)
#define  IMG_ADDR_BUTTON_HOME_ALL_PRESSED       (IMG_ADDR_BUTTON_HOME_ALL + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_HOME_X                 (IMG_ADDR_BUTTON_HOME_ALL_PRESSED + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_HOME_X_PRESSED         (IMG_ADDR_BUTTON_HOME_X + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_HOME_Y                 (IMG_ADDR_BUTTON_HOME_X_PRESSED + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_HOME_Y_PRESSED         (IMG_ADDR_BUTTON_HOME_Y + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_HOME_Z                 (IMG_ADDR_BUTTON_HOME_Y_PRESSED + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_HOME_Z_PRESSED         (IMG_ADDR_BUTTON_HOME_Z + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_MINUS_X                (IMG_ADDR_BUTTON_HOME_Z_PRESSED + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_MINUS_X_PRESSED        (IMG_ADDR_BUTTON_MINUS_X + IMG_SIZE_BUTTON_ARROW)
#define  IMG_ADDR_BUTTON_MINUS_Y                (IMG_ADDR_BUTTON_MINUS_X_PRESSED + IMG_SIZE_BUTTON_ARROW)
#define  IMG_ADDR_BUTTON_MINUS_Y_PRESSED        (IMG_ADDR_BUTTON_MINUS_Y + IMG_SIZE_BUTTON_ARROW)
#define  IMG_ADDR_BUTTON_MINUS_Z                (IMG_ADDR_BUTTON_MINUS_Y_PRESSED + IMG_SIZE_BUTTON_ARROW)
#define  IMG_ADDR_BUTTON_MINUS_Z_PRESSED        (IMG_ADDR_BUTTON_MINUS_Z + IMG_SIZE_BUTTON_ARROW)
#define  IMG_ADDR_BUTTON_PLUS_X                 (IMG_ADDR_BUTTON_MINUS_Z_PRESSED + IMG_SIZE_BUTTON_ARROW)
#define  IMG_ADDR_BUTTON_PLUS_X_PRESSED         (IMG_ADDR_BUTTON_PLUS_X + IMG_SIZE_BUTTON_ARROW)
#define  IMG_ADDR_BUTTON_PLUS_Y                 (IMG_ADDR_BUTTON_PLUS_X_PRESSED + IMG_SIZE_BUTTON_ARROW)
#define  IMG_ADDR_BUTTON_PLUS_Y_PRESSED         (IMG_ADDR_BUTTON_PLUS_Y + IMG_SIZE_BUTTON_ARROW)
#define  IMG_ADDR_BUTTON_PLUS_Z                 (IMG_ADDR_BUTTON_PLUS_Y_PRESSED + IMG_SIZE_BUTTON_ARROW)
#define  IMG_ADDR_BUTTON_PLUS_Z_PRESSED         (IMG_ADDR_BUTTON_PLUS_Z + IMG_SIZE_BUTTON_ARROW)
#define  IMG_ADDR_BUTTON_DISTANCE_1             (IMG_ADDR_BUTTON_PLUS_Z_PRESSED + IMG_SIZE_BUTTON_ARROW)
#define  IMG_ADDR_BUTTON_DISTANCE_1_PRESSED     (IMG_ADDR_BUTTON_DISTANCE_1 + IMG_SIZE_BUTTON_DISTANCE)
#define  IMG_ADDR_BUTTON_DISTANCE_5             (IMG_ADDR_BUTTON_DISTANCE_1_PRESSED + IMG_SIZE_BUTTON_DISTANCE)
#define  IMG_ADDR_BUTTON_DISTANCE_5_PRESSED     (IMG_ADDR_BUTTON_DISTANCE_5 + IMG_SIZE_BUTTON_DISTANCE)
#define  IMG_ADDR_BUTTON_DISTANCE_10            (IMG_ADDR_BUTTON_DISTANCE_5_PRESSED + IMG_SIZE_BUTTON_DISTANCE)
#define  IMG_ADDR_BUTTON_DISTANCE_10_PRESSED    (IMG_ADDR_BUTTON_DISTANCE_10 + IMG_SIZE_BUTTON_DISTANCE)
#define  IMG_ADDR_BUTTON_DISTANCE_MAX           (IMG_ADDR_BUTTON_DISTANCE_10_PRESSED + IMG_SIZE_BUTTON_DISTANCE)
#define  IMG_ADDR_BUTTON_DISTANCE_MAX_PRESSED   (IMG_ADDR_BUTTON_DISTANCE_MAX + IMG_SIZE_BUTTON_DISTANCE)
#define  IMG_ADDR_BUTTON_UNLOCK                 (IMG_ADDR_BUTTON_DISTANCE_MAX_PRESSED + IMG_SIZE_BUTTON_DISTANCE)
#define  IMG_ADDR_BUTTON_UNLOCK_PRESSED         (IMG_ADDR_BUTTON_UNLOCK + IMG_SIZE_BUTTON_NORMAL)

/* menu file */
#define  IMG_ADDR_CAPTION_FILE                  (IMG_ADDR_BUTTON_UNLOCK_PRESSED + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_PAGE_NEXT              (IMG_ADDR_CAPTION_FILE + IMG_SIZE_CAPTION)
#define  IMG_ADDR_BUTTON_PAGE_NEXT_PRESSED      (IMG_ADDR_BUTTON_PAGE_NEXT + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_PAGE_LAST              (IMG_ADDR_BUTTON_PAGE_NEXT_PRESSED + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_PAGE_LAST_PRESSED      (IMG_ADDR_BUTTON_PAGE_LAST + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_START                  (IMG_ADDR_BUTTON_PAGE_LAST_PRESSED + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_START_PRESSED          (IMG_ADDR_BUTTON_START + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_OPEN                   (IMG_ADDR_BUTTON_START_PRESSED + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_OPEN_PRESSED           (IMG_ADDR_BUTTON_OPEN + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_RETURN_FOLDER          (IMG_ADDR_BUTTON_OPEN_PRESSED + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_RETURN_FOLDER_PRESSED  (IMG_ADDR_BUTTON_RETURN_FOLDER + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_PROMPT_ERROR                  (IMG_ADDR_BUTTON_RETURN_FOLDER_PRESSED + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_INDICATOR_FILE                (IMG_ADDR_PROMPT_ERROR + IMG_SIZE_ICON_MINI)
#define  IMG_ADDR_INDICATOR_FOLDER              (IMG_ADDR_INDICATOR_FILE + IMG_SIZE_ICON_MINI)

/* menu print */
#define  IMG_ADDR_INDICATOR_HEAD                (IMG_ADDR_INDICATOR_FOLDER + IMG_SIZE_ICON_MINI)
#define  IMG_ADDR_INDICATOR_FAN_0               (IMG_ADDR_INDICATOR_HEAD + IMG_SIZE_ICON_MINI)
#define  IMG_ADDR_INDICATOR_FAN_1               (IMG_ADDR_INDICATOR_FAN_0 + IMG_SIZE_ICON_MINI)
#define  IMG_ADDR_INDICATOR_BED                 (IMG_ADDR_INDICATOR_FAN_1 + IMG_SIZE_ICON_MINI)
#define  IMG_ADDR_INDICATOR_HEIGHT              (IMG_ADDR_INDICATOR_BED + IMG_SIZE_ICON_MINI)
#define  IMG_ADDR_INDICATOR_TIMER_CD            (IMG_ADDR_INDICATOR_HEIGHT + IMG_SIZE_ICON_MINI)
#define  IMG_ADDR_INDICATOR_TIMER_CU            (IMG_ADDR_INDICATOR_TIMER_CD + IMG_SIZE_ICON_MINI)
#define  IMG_ADDR_BUTTON_PAUSE                  (IMG_ADDR_INDICATOR_TIMER_CU + IMG_SIZE_ICON_MINI)
#define  IMG_ADDR_BUTTON_PAUSE_PRESSED          (IMG_ADDR_BUTTON_PAUSE + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_PAUSE_DISABLE          (IMG_ADDR_BUTTON_PAUSE_PRESSED + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_RESUME                 (IMG_ADDR_BUTTON_PAUSE_DISABLE + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_RESUME_PRESSED         (IMG_ADDR_BUTTON_RESUME + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_RESUME_DISABLE         (IMG_ADDR_BUTTON_RESUME_PRESSED + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_ADJUST                 (IMG_ADDR_BUTTON_RESUME_DISABLE + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_ADJUST_PRESSED         (IMG_ADDR_BUTTON_ADJUST + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_END                    (IMG_ADDR_BUTTON_ADJUST_PRESSED + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_END_PRESSED            (IMG_ADDR_BUTTON_END + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_PROMPT_COMPLETE               (IMG_ADDR_BUTTON_END_PRESSED + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_PROMPT_PAUSE                  (IMG_ADDR_PROMPT_COMPLETE + IMG_SIZE_ICON_MINI)
#define  IMG_ADDR_PROMPT_PRINTING               (IMG_ADDR_PROMPT_PAUSE + IMG_SIZE_ICON_MINI)
#define  IMG_ADDR_PROMPT_RECOVERY               (IMG_ADDR_PROMPT_PRINTING + IMG_SIZE_ICON_MINI)
#define  IMG_ADDR_PROMPT_WARNING                (IMG_ADDR_PROMPT_RECOVERY + IMG_SIZE_ICON_MINI)
#define  IMG_ADDR_PROMPT_HEATING                (IMG_ADDR_PROMPT_WARNING + IMG_SIZE_ICON_MINI)

/* menu adjust */
#define  IMG_ADDR_CAPTION_ADJUST                (IMG_ADDR_PROMPT_HEATING + IMG_SIZE_ICON_MINI)
#define  IMG_ADDR_BUTTON_ADD                    (IMG_ADDR_CAPTION_ADJUST + IMG_SIZE_CAPTION)
#define  IMG_ADDR_BUTTON_ADD_PRESSED            (IMG_ADDR_BUTTON_ADD + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_SUB                    (IMG_ADDR_BUTTON_ADD_PRESSED + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_SUB_PRESSED            (IMG_ADDR_BUTTON_SUB + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_INDICATOR_SPEED               (IMG_ADDR_BUTTON_SUB_PRESSED + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_INDICATOR_FLOW                (IMG_ADDR_INDICATOR_SPEED + IMG_SIZE_ICON_MINI)

/* menu preheating */
#define  IMG_ADDR_CAPTION_PREHEAT               (IMG_ADDR_INDICATOR_FLOW + IMG_SIZE_ICON_MINI)
#define  IMG_ADDR_BUTTON_COOLING                (IMG_ADDR_CAPTION_PREHEAT + IMG_SIZE_CAPTION)
#define  IMG_ADDR_BUTTON_COOLING_PRESSED        (IMG_ADDR_BUTTON_COOLING + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_FILAMENT_0             (IMG_ADDR_BUTTON_COOLING_PRESSED + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_FILAMENT_0_PRESSED     (IMG_ADDR_BUTTON_FILAMENT_0 + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_FILAMENT_1             (IMG_ADDR_BUTTON_FILAMENT_0_PRESSED + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_FILAMENT_1_PRESSED     (IMG_ADDR_BUTTON_FILAMENT_1 + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_FILAMENT_2             (IMG_ADDR_BUTTON_FILAMENT_1_PRESSED + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_FILAMENT_2_PRESSED     (IMG_ADDR_BUTTON_FILAMENT_2 + IMG_SIZE_BUTTON_NORMAL)

/* menu leveling */
#define  IMG_ADDR_CAPTION_LEVELING              (IMG_ADDR_BUTTON_FILAMENT_2_PRESSED + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_LEVELING0              (IMG_ADDR_CAPTION_LEVELING + IMG_SIZE_CAPTION)
#define  IMG_ADDR_BUTTON_LEVELING0_PRESSED      (IMG_ADDR_BUTTON_LEVELING0 + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_LEVELING1              (IMG_ADDR_BUTTON_LEVELING0_PRESSED + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_LEVELING1_PRESSED      (IMG_ADDR_BUTTON_LEVELING1 + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_LEVELING2              (IMG_ADDR_BUTTON_LEVELING1_PRESSED + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_LEVELING2_PRESSED      (IMG_ADDR_BUTTON_LEVELING2 + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_LEVELING3              (IMG_ADDR_BUTTON_LEVELING2_PRESSED + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_LEVELING3_PRESSED      (IMG_ADDR_BUTTON_LEVELING3 + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_LEVELING4              (IMG_ADDR_BUTTON_LEVELING3_PRESSED + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_LEVELING4_PRESSED      (IMG_ADDR_BUTTON_LEVELING4 + IMG_SIZE_BUTTON_NORMAL)

/* menu extrude */
#define  IMG_ADDR_CAPTION_EXTRUDE               (IMG_ADDR_BUTTON_LEVELING4_PRESSED + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_MINUS_E                (IMG_ADDR_CAPTION_EXTRUDE + IMG_SIZE_CAPTION)
#define  IMG_ADDR_BUTTON_MINUS_E_PRESSED        (IMG_ADDR_BUTTON_MINUS_E + IMG_SIZE_BUTTON_ARROW)
#define  IMG_ADDR_BUTTON_PLUS_E                 (IMG_ADDR_BUTTON_MINUS_E_PRESSED + IMG_SIZE_BUTTON_ARROW)
#define  IMG_ADDR_BUTTON_PLUS_E_PRESSED         (IMG_ADDR_BUTTON_PLUS_E + IMG_SIZE_BUTTON_ARROW)
#define  IMG_ADDR_BUTTON_FEED_IN_0              (IMG_ADDR_BUTTON_PLUS_E_PRESSED + IMG_SIZE_BUTTON_ARROW)
#define  IMG_ADDR_BUTTON_FEED_IN_0_PRESSED      (IMG_ADDR_BUTTON_FEED_IN_0 + IMG_SIZE_BUTTON_FEED)
#define  IMG_ADDR_BUTTON_FEED_IN_1              (IMG_ADDR_BUTTON_FEED_IN_0_PRESSED + IMG_SIZE_BUTTON_FEED)
#define  IMG_ADDR_BUTTON_FEED_IN_1_PRESSED      (IMG_ADDR_BUTTON_FEED_IN_1 + IMG_SIZE_BUTTON_FEED)
#define  IMG_ADDR_BUTTON_FEED_OUT_0             (IMG_ADDR_BUTTON_FEED_IN_1_PRESSED + IMG_SIZE_BUTTON_FEED)
#define  IMG_ADDR_BUTTON_FEED_OUT_0_PRESSED     (IMG_ADDR_BUTTON_FEED_OUT_0 + IMG_SIZE_BUTTON_FEED)
#define  IMG_ADDR_BUTTON_FEED_OUT_1             (IMG_ADDR_BUTTON_FEED_OUT_0_PRESSED + IMG_SIZE_BUTTON_FEED)
#define  IMG_ADDR_BUTTON_FEED_OUT_1_PRESSED     (IMG_ADDR_BUTTON_FEED_OUT_1 + IMG_SIZE_BUTTON_FEED)
#define  IMG_ADDR_BUTTON_FEED_STOP              (IMG_ADDR_BUTTON_FEED_OUT_1_PRESSED + IMG_SIZE_BUTTON_FEED)
#define  IMG_ADDR_BUTTON_FEED_STOP_PRESSED      (IMG_ADDR_BUTTON_FEED_STOP + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_BED_ON                 (IMG_ADDR_BUTTON_FEED_STOP_PRESSED + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_BED_ON_PRESSED         (IMG_ADDR_BUTTON_BED_ON + IMG_SIZE_BUTTON_BED)
#define  IMG_ADDR_BUTTON_BED_OFF                (IMG_ADDR_BUTTON_BED_ON_PRESSED + IMG_SIZE_BUTTON_BED)
#define  IMG_ADDR_BUTTON_BED_OFF_PRESSED        (IMG_ADDR_BUTTON_BED_OFF + IMG_SIZE_BUTTON_BED)

/* menu settings */
#define  IMG_ADDR_CAPTION_SETTINGS              (IMG_ADDR_BUTTON_BED_OFF_PRESSED + IMG_SIZE_BUTTON_BED)
#define  IMG_ADDR_BUTTON_MODIFY                 (IMG_ADDR_CAPTION_SETTINGS + IMG_SIZE_CAPTION)
#define  IMG_ADDR_BUTTON_MODIFY_PRESSED         (IMG_ADDR_BUTTON_MODIFY + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_RESTORE                (IMG_ADDR_BUTTON_MODIFY_PRESSED + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_RESTORE_PRESSED        (IMG_ADDR_BUTTON_RESTORE + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_SAVE                   (IMG_ADDR_BUTTON_RESTORE_PRESSED + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_SAVE_PRESSED           (IMG_ADDR_BUTTON_SAVE  + IMG_SIZE_BUTTON_NORMAL)

/* menu about */
#define  IMG_ADDR_CAPTION_ABOUT                 (IMG_ADDR_BUTTON_SAVE_PRESSED + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_AIMING                 (IMG_ADDR_CAPTION_ABOUT + IMG_SIZE_CAPTION)
#define  IMG_ADDR_BUTTON_AIMING_PRESSED         (IMG_ADDR_BUTTON_AIMING + IMG_SIZE_BUTTON_NORMAL)

/* menu language */
#define  IMG_ADDR_CAPTION_LANGUAGE              (IMG_ADDR_BUTTON_AIMING_PRESSED + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_ENGLISH                (IMG_ADDR_CAPTION_LANGUAGE + IMG_SIZE_CAPTION)
#define  IMG_ADDR_BUTTON_ENGLISH_PRESSED        (IMG_ADDR_BUTTON_ENGLISH + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_CHINESE                (IMG_ADDR_BUTTON_ENGLISH_PRESSED + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_CHINESE_PRESSED        (IMG_ADDR_BUTTON_CHINESE + IMG_SIZE_BUTTON_NORMAL)

/* dialog */
#define  IMG_ADDR_DIALOG_BODY                   (IMG_ADDR_BUTTON_CHINESE_PRESSED + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_YES                    (IMG_ADDR_DIALOG_BODY + IMG_SIZE_DIALOG_BODY)
#define  IMG_ADDR_BUTTON_YES_PRESSED            (IMG_ADDR_BUTTON_YES + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_NO                     (IMG_ADDR_BUTTON_YES_PRESSED + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_BUTTON_NO_PRESSED             (IMG_ADDR_BUTTON_NO + IMG_SIZE_BUTTON_NORMAL)
#define  IMG_ADDR_PROMPT_QUESTION               (IMG_ADDR_BUTTON_NO_PRESSED + IMG_SIZE_BUTTON_NORMAL)

/* launch logo "iFormer" */
#define  IMG_ADDR_STARTUP_LOGO_1                (IMG_ADDR_PROMPT_QUESTION + IMG_SIZE_ICON_MINI)

/* launch logo "LONGER" */
#define  IMG_ADDR_STARTUP_LOGO_2                (IMG_ADDR_STARTUP_LOGO_1 + IMG_SIZE_LOGO1)  //991586

//#define  FONT16_ADDR_GBK                        (0x000F6950 )      //992000 =  0x000F2300

/* image address definition end */
//#define  IMG_MAX_ADDR                           (IMG_ADDR_STARTUP_LOGO_2 + IMG_SIZE_LOGO2)   //1009994
